l_english:
 SETTING_DEBUG_SAVES:0 "Número de salvamentos de depuração"
 SETTING_TUTORIAL:0 "Tutorial"
 SETTING_DISABLED_HINTS:0 "dicas desativadas"
 SETTING_FOCUS_ON_COMBAT:0 "Foco no combate"
 SETTING_TOOLTIP_DELAY:1 "Atraso da dica de ferramenta"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!Define o atraso antes que as dicas de ferramentas apareçam."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "atraso de desbloqueio"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!Define o atraso antes que as dicas de ferramentas sejam desbloqueadas."
 SETTING_TOOLTIP_LOCK_TIME:0 "Atraso de Bloqueio"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!Define o atraso antes que as dicas de ferramentas sejam bloqueadas."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Retardo Aberto Bloqueado"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!Define o atraso antes que as dicas de ferramentas sejam bloqueadas quando outra dica de ferramenta já estiver aberta."
 # Audio
 SETTING_Sound_Effects:1 "Todos os efeitos sonoros"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Volume dos Efeitos Sonoros\n#!Define o volume de TODOS os efeitos sonoros."
 SETTING_Ambience:0 "Ambiente"
 SETTING_Ambience_TOOLTIP:1 "#T Volume Ambiente\n#!Define o volume do ambiente ambiente."
 SETTING_TOOLTIP_MODE:1 "Modo dica"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!Define as dicas de ferramentas de maneira "lock in," enabling tooltips-in-tooltips."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Tendência do mouse"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips automatically trancar place until the cursor moves away."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Bloqueio de Ação"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!Pressione #V do meio do mouse#! para bloquear e desbloquear dicas de ferramentas."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Bloqueio do Temporizador"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips are locked in place if the cursor does not move for a short while. #weak (Default setting.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Diversos"
 SETTINGS_CATEGORY_TOOLTIPS:0 "dicas"
 SETTINGS_CATEGORY_SFX:0 "Efeitos Sonoros Específicos"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Em geral"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Controles do Mapa"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Salvar jogos"
 SETTINGS_CATEGORY_LANGUAGE:0 "Linguagem"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avançado – Geral"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "Avançado – Mapa"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "Avançado – Personagens"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Retratos"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "Multijogador"
 SETTINGS_CATEGORY_MAP:0 "Mapa"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Mostrar doenças e lesões gráficas"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!Define se lesões e doenças gráficas serão visíveis em retratos de personagens."
 SETTING_SHOW_NUDITY:0 "mostrar nudez"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!Define se os personagens podem ser mostrados nus."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "Panela ociosa da corte real"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!Determina se a câmera na Corte Real deve fazer uma panorâmica suave em sua Corte quando ociosa.\nSe os Personagens Animados estiverem desativados, essa configuração não terá efeito."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "Transições Suaves da Corte Real"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!Determina se a câmera no Royal Court deve se mover suavemente para um novo local.\nSe os Personagens Animados estiverem desativados, essa configuração não terá efeito."
 NEVER:0 "Nunca"
 MONTHLY:0 "Todo mês"
 HALFYEAR:0 "A cada 6 meses"
 YEARLY:0 "Todo ano"
 FIVE_YEAR:0 "A cada 5 anos"
 SETTINGS_CATEGORY_TUTORIAL:0 "Tutorial"
 SETTING_REACTIVE_TUTORIAL:1 "Mostrar conselho reativo"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!Define se o jogo deve mostrar o conselho do tutorial reagindo à forma como você joga. Útil para jogadores novos no Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Mostrar sugestões"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!Define se o jogo deve sugerir algo para fazer em intervalos regulares. Útil para jogadores novos no Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Redefinir conselho reativo"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Redefinir aviso reativo#!Os conselhos reativos vistos anteriormente aparecerão mais uma vez."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Redefinir conselho reativo"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Tem certeza de que deseja redefinir o aviso reativo?"
 SETTING_ADVANCED_SHADERS:0 "Efeitos avançados de sombreamento"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Efeitos Shader Avançados\n#!Esta opção habilitará efeitos de sombreamento avançados.\nDesligá-lo pode aumentar o desempenho ao custo de fazer alguns efeitos (por exemplo, terreno e água) parecerem piores"
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Efeitos de partículas de inverno"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!Determina se os efeitos de partículas são mostrados ou não quando o inverno está ativo em algumas áreas do mapa.\nDesligá-lo pode aumentar o desempenho"
 SETTING_RESET_CAMERA_ROTATION:0 "Redefinição da rotação da câmera"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!Determina se a câmera deve redefinir automaticamente a posição padrão após ser girada pelo usuário"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "Personagens de plano de fundo da cena do tribunal"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!Determina se a cena 3D do Royal Court deve exibir personagens de fundo menos importantes."
 SETTING_MAP_HIGHLIGHT:0 "Destaque do Cursor do Mapa"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!Determina a intensidade dos destaques do cursor no mapa"
 BASED_ON_ZOOM_LEVEL:0 "Dinâmico"
 ALWAYS_HIDE:0 "Sempre esconda"
 ALWAYS_SHOW:0 "Sempre aparece"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Fronteiras Costeiras"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!Esta opção controlará quando as bordas do reino costeiro devem ser mostradas.Se $BASED_ON_ZOOM_LEVEL$ então eles ficarão ocultos no nível de zoom de detalhes.\nEscolher um $ALWAYS_SHOW$ ou $ALWAYS_HIDE$ pode aumentar o desempenho ao custo das fronteiras do reino costeiro não se escondendo dinamicamente."
 SETTINGS_DISCARD_CHANGES:0 "Descartar mudanças"
